/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "LogicalPathApiImpl.h"
#include <string>

#include "utils.hpp"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    LogicalPathApiImpl::LogicalPathApiImpl(Pistache::Address addr)
        : LogicalPathApi(addr)
        , irods_logical_path_delete_{}
        , irods_logical_path_rename_{}
    {
    }

    void LogicalPathApiImpl::handler_impl(const Pistache::Rest::Request& request,
                                   Pistache::Http::ResponseWriter& response)
    {

    }

    void LogicalPathApiImpl::delete_handler_impl(const Pistache::Rest::Request& request,
                                    Pistache::Http::ResponseWriter& response
                                    )
    {
        irods::rest::handle_request(irods_logical_path_delete_, request, response);
    }

    void LogicalPathApiImpl::rename_handler_impl(const Pistache::Rest::Request& request,
                                        Pistache::Http::ResponseWriter& response )
    {
        irods::rest::handle_request(irods_logical_path_rename_, request, response);
    }
} // namespace io::swagger::server::api

