/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* LogicalPathApiImpl.h
*
*
*/

#ifndef LOGICAL_PATH_API_IMPL_H_
#define LOGICAL_PATH_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>

#include "ModelBase.h"

#include <LogicalPathApi.h>
#include <irods_rest_logical_path_delete_api_implementation.h>
#include <irods_rest_logical_path_rename_api_implementation.h>
#include <irods_rest_logical_path_bulk_api_implementation.h>

#include <memory>
#include <string>


namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    class LogicalPathApiImpl
        : public io::swagger::server::api::LogicalPathApi
    {
    public:
        LogicalPathApiImpl(Pistache::Address addr);

        ~LogicalPathApiImpl() = default;

        void handler_impl(const Pistache::Rest::Request& request,
                          Pistache::Http::ResponseWriter& response) override;

        void rename_handler_impl(const Pistache::Rest::Request& request,
                                          Pistache::Http::ResponseWriter& response) override;

        void delete_handler_impl(const Pistache::Rest::Request& request,
                                       Pistache::Http::ResponseWriter& response) override;

        irods::rest::logical_path_delete irods_logical_path_delete_;
        irods::rest::logical_path_rename irods_logical_path_rename_;
        irods::rest::logical_path_bulk irods_logical_path_bulk_;
    }; // class LogicalPathApiImpl
} // namespace io::swagger::server::api

#endif // LOGICAL_PATH_API_IMPL_H_

